services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d fintrack"]
      interval: 5s
      retries: 10

volumes:
  pgdata: